/*
DROP TABLE specificrentals
DROP TABLE rental
DROP TABLE equipmentsbills
DROP TABLE bills
DROP TABLE cashiers
DROP TABLE equipments
*/

CREATE TABLE equipments ( 
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1) ,
	model VARCHAR(12) NOT NULL UNIQUE , 
	name VARCHAR(32) NOT NULL , 
	brandName VARCHAR(32) NOT NULL , 
	size VARCHAR(10) NOT NULL , 
	isRental BIT NOT NULL DEFAULT 0 , 
	isOnShelf BIT NOT NULL DEFAULT 0 , 
	price MONEY NOT NULL , 
	inStock INT NOT NULL DEFAULT 0);


CREATE TABLE cashiers ( 
	ID INT NOT NULL PRIMARY KEY IDENTITY (1,1) , 
	pesel VARCHAR(11) NOT NULL , 
	name VARCHAR(32) NOT NULL , 
	surname VARCHAR(32) NOT NULL , 
	dateOfEmployment DATE NOT NULL DEFAULT CURRENT_TIMESTAMP);


CREATE TABLE bills ( 
	billNumber BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1) , 
	cashierID INT NOT NULL DEFAULT '-1' FOREIGN KEY REFERENCES cashiers (ID), 
	amount MONEY NOT NULL , 
	paymentDatetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);


CREATE TABLE equipmentsbills ( 
	ID INT NOT NULL PRIMARY KEY IDENTITY (1,1) , 
	billNumber BIGINT NOT NULL FOREIGN KEY REFERENCES bills (billNumber), 
	equipmentID BIGINT NOT NULL FOREIGN KEY REFERENCES equipments (ID), 
	amountPaid INT NOT NULL);


CREATE TABLE rental ( 
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1) , 
	billNumber BIGINT NOT NULL FOREIGN KEY REFERENCES bills (billNumber), 
	isReturned BIT NOT NULL DEFAULT 0 , 
	name VARCHAR(32) NOT NULL , surname VARCHAR(32) NOT NULL);
	

CREATE TABLE specificrentals ( 
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1) , 
	rentalID BIGINT NOT NULL FOREIGN KEY REFERENCES rental (ID), 
	equipmentID BIGINT NOT NULL FOREIGN KEY REFERENCES equipments (ID), 
	startDatetime DATETIME NOT NULL , 
	plannedEndDatetime DATETIME NOT NULL , 
	actualEndDatetime DATETIME NOT NULL , 
	moneyOwed INT NOT NULL DEFAULT '0');